### ISSUE TITLE
PyNest package does not work.

### ISSUE THREAD

**Issue by brenthuisman** [neurofedora/Issues#1]
On a fresh Fedora 32, I ran `sudo dnf install python3-nest`. Starting Python and then `import nest`, I get the following:
```
    [14:17:33 last:0s ~] python
    Python 3.8.5 (default, Aug 12 2020, 00:00:00)
    [GCC 10.2.1 20200723 (Red Hat 10.2.1-1)] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import nest
    [INFO] [2020.8.25 14:17:38 /builddir/build/BUILD/nest-simulator-2.20.0/nest-simulator-2.20.0/nestkernel/rng_manager.cpp:217 @ Network::create_rngs_] : Creating default RNGs
    [INFO] [2020.8.25 14:17:38 /builddir/build/BUILD/nest-simulator-2.20.0/nest-simulator-2.20.0/nestkernel/rng_manager.cpp:260 @ Network::create_grng_] : Creating new default global RNG

    Aug 25 14:17:38 SLIStartup [Fatal]:
        Your NEST installation seems broken.


    Aug 25 14:17:38 SLIStartup [Fatal]:
        I could not find the startup file that

    Aug 25 14:17:38 SLIStartup [Fatal]:
        should have been in /home/brent/.local/share/nest

    Aug 25 14:17:38 SLIStartup [Fatal]:
        Please re-build NEST and try again.

    Aug 25 14:17:38 SLIStartup [Fatal]:
        The file install.html in NEST's doc directory tells you how.

    Aug 25 14:17:38 SLIStartup [Fatal]:
        Bye.
    >>>
```

I tried the above with also either the `python3-nest-mpich` and `python3-nest-openmpi` packages to no effect.

**Comment by sanjayankur31** [comment]
Hi @brenthuisman, thanks for the report. 

I'm not seeing the issue here:

```
$ rpm -q python3-nest
python3-nest-2.20.0-1.fc32.x86_64

$ python
Python 3.8.5 (default, Aug 12 2020, 00:00:00) 
[GCC 10.2.1 20200723 (Red Hat 10.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
(ins)>>> import nest
[INFO] [2020.8.25 13:58:16 /builddir/build/BUILD/nest-simulator-2.20.0/nest-simulator-2.20.0/nestkernel/rng_manager.cpp:217 @ Network::create_rngs_] : Creating default RNGs
[INFO] [2020.8.25 13:58:16 /builddir/build/BUILD/nest-simulator-2.20.0/nest-simulator-2.20.0/nestkernel/rng_manager.cpp:260 @ Network::create_grng_] : Creating new default global RNG

              -- N E S T --
  Copyright (C) 2004 The NEST Initiative

 Version: nest-2.20.0
 Built: Feb  1 2020 00:00:00

 This program is provided AS IS and comes with
 NO WARRANTY. See the file LICENSE for details.

 Problems or suggestions?
   Visit https://www.nest-simulator.org

 Type 'nest.help()' to find out more about NEST.

(ins)>>> 

```

I do not have a startup file in `~/.local/share/nest` either. I'll go grab a live image too and see what I get there. In the meantime, could you provide the outputs of these commands please?

- `rpm -qa \*nest\*`
- `uname -a`

**Comment by brenthuisman** [comment]
hi @sanjayankur31!

```
[15:09:46 last:0s ~] rpm -qa \*nest\*
nest-common-2.20.0-1.fc32.noarch
nest-2.20.0-1.fc32.x86_64
python3-nest-2.20.0-1.fc32.x86_64
texlive-nestquot-svn27323.0-19.fc32.noarch
[15:11:31 last:1s ~] uname -a
Linux dell7400 5.7.16-200.fc32.x86_64 #1 SMP Wed Aug 19 16:58:53 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

Thanks for looking into it! (Meanwhile I've compiled PyNest myself successfully.)

**Comment by sanjayankur31** [comment]
Thanks. That looks OK.

I've downloaded the released Fedora 32 image and tried this out, and it worked fine there too. So it seems to be something system specific:

![Screenshot from 2020-08-25 14-12-28](https://user-images.githubusercontent.com/102575/91178965-cece2a00-e6dd-11ea-9982-277c83571296.png)

Could you please check if any environment variables related to NEST are set? With the NeuroFedora package, they don't need to be since all files go in the standard directories as required by the [Filesystem Hierarchy Standard](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard).

```
$ env | grep -i nest
```

**Comment by brenthuisman** [comment]
After logging out and in to make sure the `nest_vars.sh` form my own compile were no longer loaded:
```
[15:30:10 last:0s ~] env | grep -i nest
[15:30:11 last:0s ~]
```
However, now also `import nest` does function! PyNest from the package is loaded, not my compile. Not sure what happened, I guess a logout/-in helped.

**Comment by sanjayankur31** [comment]
That's good to know. Thanks for confirming. It must've been a shell quirk. I tend to at least close and re-open the terminal if I've been tinkering with environment variables since they create such weird issues.

The neurofedora package also provides `/usr/bin/nest_vars.sh`, so you can use that to switch between your compiled version and the package if you're developing and so on for example. It simply sets the variables to the system paths.

Thanks for filing the issue. Please do file more if you see any other bugs.
